
server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.112:3306/shopping?useUnicode=true&characterEncoding=utf8&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instance-id: product-service
      prefer-ip-address: true   #访问路径可以显示IP地址
